### PR TITLE
Fixes issue where no songs show up in playlists

### LINKED ISSUE #21: No songs show up in playlists
It seems like `Entries` in `SubsonicPlaylist` does not get populated with songs when calling `GetPlaylists`.
I feel like I am missing something as to how playlist songs are fetched, considering no songs are fetched in this [example](http://www.subsonic.org/pages/inc/api/examples/playlists_example_1.xml) on getPlaylists from the subsonic api docs.

One solution would be using GetPlaylist to fetch the songs in each playlist and put them into respective playlist. This works, but I'm not sure how it even works to begin with due to reasons stated above.

Anyhow, I'd be happy to help.

### PR DESCRIPTION
**Pull request by Virtuo1**
Closes #21

### CODE REVIEW

**Comment by wildeyedskies** [comment]
This change is throwing a null pointer when I attempt to run it. Unsure why, will investigate
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x732695]

goroutine 1 [running]:
main.main()
	/home/zoe/Code/stmp/stmp.go:44 +0x155
exit status 2
```

**Comment by Virtuo1** [comment]
Any progress on this? :) Probably an error in GetPlaylists() resulting in it returning nil, if I had to guess. What does the error say if you print it?
```
playlistResponse, err := connection.GetPlaylists()
println(err)
```
Another thought: maybe an error here should always be printed to the user as it might provide more useful information rather than a null pointer error.

**Comment by wildeyedskies** [comment]
The error I'm getting is this `json: cannot unmarshal number into Go struct field SubsonicPlaylist.subsonic-response.playlists.playlist.id of type string` I think maybe the client I'm using (gonic) is using strings for their playlist ids when they shouldn't be

**Comment by dweymouth** [comment]
Just FYI the subsonic API documentation does not restrict IDs to be integers. The original Subsonic implementation did use ints for IDs but there is no reason to expect that all other Subsonic-compatible servers would do the same. Ideally your code should be written to accept any arbitrary strings as IDs.

**Comment by Virtuo1** [comment]
Commit [9371311](https://github.com/wildeyedskies/stmp/pull/22/commits/937131127b4c8d79d8ae5f0be489556c0a0abb57) fixes that. This change has been tested with a navidrome and subsonic server, and it works on my end. I can't test this on a gonic server however, as I don't run one.

**Pull request closed without merging**
